const destinations = [
  {
    id: 1,
    nama: "Kota Tua",
    deskripsi:
      "Jika anda tidak menyukai tempat wisata yang berisik dan terlalu kekanak-kanakan, mungkin Anda bisa mencoba ke Kota Tua! Destinasi wisata ini menyimpan segudang pengetahuan sejarah yang dapat menjadi wawasan baru bagimu. Gedung-gedung di wilayah tersebut berupa peninggalan bangunan-bangunan tua bergaya kolonial Belanda yang begitu menawan. Terletak di sebelah utara dari pusat jakarta, kota tua dapat dijangkau melalui berbagai moda transportasi umum seperti bus Transjakarta, KRL Commuter Line, dan MRT Jakarta.\n\nDengan berjalan diantara bangunan-bangunan bersejarah di Kota Tua, Anda dapat merasakan suasana zaman dulu yang dirasakan oleh nenek moyang. Selain itu, terdapat beberapa warung-warung tradisional yang menyediakan hidangan khas. Jika merasa lelah untuk mengelilingi Kota Tua tersebut dengan berjalan kaki, Anda dapat menyewa sepeda ontel yang pastinya mudah untuk ditemukan disana.\n\nMungkin pada saat Anda menjelajahi Kota Tua, Anda akan menemukan museum Fatahillah, museum yang merupakan bekas balai kota sekaligus sebagai tempat pengadilan yang dilengkapi dengan penjara bawah tanah. Selain museum Fatahillah, terdapat berbagai tempat yang patut dikunjungi seperti museum Wayang, museum Seni Rupa dan Keramik, museum Bank Indonesia, dan sebagainya. Daripada membayangkan dari pikiranmu, lebih baik Anda mencoba rasakan sendiri betapa mengagumkan tempat-tempat tersebut! Kota Tua menunggu kedatangan Anda!",
    kategori: "Sejarah, Seni & Budaya",
    lokasi: "Jakarta Barat",
    Alamat: "Jl Kalibesar Timur No. 30 Kel. Pinangsia",
    Instagram: "@kotatua,jkt",
    JamOp: "",
    image: "/assets/kotu-hero.jpg",
    images: [
      "/assets/kotu.png",
      "/assets/kotu1.jpg",
      "/assets/kotu2.jpg",
      "/assets/kotu3.jpg",
      "/assets/kotu4.jpeg",
      "/assets/kotu5.jpg",
    ],
    route_jaklingko: "",
    route_krl: "/assets/rute-TMII.png",
  },
  {
    id: 2,
    nama: "Taman Mini Indonesia Indah (TMII)",
    deskripsi:
      "Bingung menghabiskan waktu liburan dimana? TMII jawabnya! TMII atau Taman Mini Indonesia Indah adalah salah satu tempat wisata yang wajib kalian kunjungi. Bertempat di Jakarta Timur dan memiliki area seluas ±  147 hektare atau 1,47 kilometer persegi.\n\nDestinasi wisata yang mempersembahkan kekayaan budaya, keberagaman serta keindahan alam Nusantara dalam satu tempat. Kalian bisa menikmati perjalanan yang menakjubkan melintasi 34 provinsi, dengan replika bangunan, tarian, dan kebudayaan unik setiap daerah.\n\nDisamping itu, di tengah-tengah TMII terdapat sebuah danau yang menggambarkan miniatur kepulauan Indonesia di tengahnya, kereta gantung, berbagai museum, dan Teater IMAX Keong Mas dan Teater Tanah Airku), berbagai sarana rekreasi ini menjadikan TMIII sebagai salah satu kawasan wisata terkemuka di ibu kota.\n\nMari rasakan keajaiban alam, kekayaan budaya, dan keindahan arsitektur tradisional yang memikat hati di setiap sudutnya. Temukan pesona Indonesia dari Sabang hingga Merauke di Taman Mini Indonesia Indah (TMII)!!!",
    kategori: "Taman Hiburan dan Edukasi",
    lokasi: "Jakarta Timur",
    Alamat: "Jl. Taman Mini Indonesia Indah, Ceger, Kec. Cipayung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13820",
    Instagram: "@tmiiofficial",
    JamOp: "05.00 - 20.00 WIB",
    image: "/assets/tmii.png",
    images: [
      "/assets/TMII.jpg",
      "/assets/TMII1.jpg",
      "/assets/TMII2.jpg",
      "/assets/",
      "/assets/",
      "/assets/",
    ],
    route_jaklingko: "",
    route_krl: "/assets/rute-TMII.png",
  },
  {
    id: 3,
    nama: "Dunia Fantasi (Dufan)",
    deskripsi:
      "Habis diputusin pacar atau sedang melewati masa sulit? Mungkin Anda bisa mencoba meluapkan emosi dan rasa kesalmu dengan berteriak di tempat ini! Dufan yang merupakan singkatan dari Dunia Fantasi, menyediakan berbagai wahana permainan yang spektakuler dan menantang.\n\nDufan terdiri dari berbagai kawasan bertema yang menakjubkan. Salah satu yang paling populer adalah Dunia Khayalan yang menampilkan wahana-wahana ekstrem seperti roller coaster Halilintar, Cyclone, dan Bianglala raksasa. Bagi yang kurang menyukai ketinggian, ada pula wahana Terros yang memacu adrenalin dengan jalur melingkar berliku. Tidak ketinggalan pula Dunia Petualangan yang menghadirkan suasana hutan belantara dengan animatronik binatang buas dalam wahana Hutan Kaya.\n\nSetelah merasa lelah dengan wahana ekstrem, Anda dapat bermain wahana komedi putar yang membuat anda lebih rileks sehabis berteriak. Sensasi memutar dan berputar dalam wahana ini akan membantu melepaskan ketegangan dan membuat Anda merasa lebih segar. Nikmati keseruan tanpa batas di taman rekreasi ikonik ini yang akan selalu menyajikan pengalaman tak terlupakan bagi setiap pengunjungnya.",
    kategori: "Taman Hiburan",
    lokasi: "Jakarta Utara",
    Alamat: "Jl. Lodan Timur No.7, Ancol, Kec. Pademangan, Jkt Utara, Daerah Khusus Ibukota Jakarta 14430",
    Instagram: "@infodufan",
    JamOp: "Senin - Jumat	: 10.00 - 17.00 WIB \nSabtu - Minggu : 10.00 - 19.00 WIB",
    image: "/assets/dufan.webp",
    images: [
      "/assets/dufan.jpeg",
      "/assets/dufan1.jpg",
      "/assets/dufan2.jpg",
      "/assets/dufan3.png",
      "/assets/",
      "/assets/",
    ],
  },
  {
    id: "4",
    nama: "Taman Impian Jaya Ancol",
    deskripsi:
      "Taman Impian Jaya Ancol adalah taman rekreasi tematik terbesar dan terlengkap di Jakarta. Terletak di Jakarta Utara berhadapan dengan Laut Jawa, Taman Impian Jaya Ancol merupakan kawasan resor tepi pantai yang berdiri di atas lahan seluas 80 hektar. Ini adalah sebuah taman rekreasi yang menyediakan berbagai fasilitas, mulai dari olahraga air dan pantai, wahana seru, kolam renang, hingga Eco-Park dan pertunjukan spertakuler bertabur bintang kaliber internasional.\n\nDunia Fantasy (Dufan) menawarkan 27 wahana mengasyikkan, antara lain roller coaster raksasa, air terjun Niagara, Tornado, dan juga Istana Boneka. Di Atlantis Water Adventure terdapat 8 kolam renang berukuran besar yang dilengkapi dengan efek ombak dan wahana seluncur.\n\nAda pula Seaworld, dimana Anda bisa berjalan di bawah terowongan kaca sambil menyaksikan maraknya kehidupan di bawah air. Selain itu, di sini terdapat pula Pasar Seni, Eco-Park, Ocean Park, serta tiga buah hotel berbintang dimana Anda bisa menikmati liburan dan akhir pekan dalam kenyamanan bungalow di tepi pantai atau mengadakan rapat di tempat yang jauh dari hiruk-pikuknya kehidupan kota.\n\nMari kita berpetualang dan jelajahi keanekaragaman atraksi, mulai dari Atlantis Water Adventure hingga keasyikan Dunia Fantasi. Rasakan keseruan yang tiada akhir dan temukan keajaiban lainnya di Taman Impian Jaya Ancol!",
    kategori: "Taman Hiburan",
    lokasi: "Jakarta Utara",
    Alamat: "Jl. Lodan Timur No.7, Ancol, Kec. Pademangan, Jkt Utara, Daerah Khusus Ibukota Jakarta 14430",
    Instagram: "",
    JamOp: "06.00 - 18.00 WIB",
    image: "/assets/ancol.jpeg",
    images: [
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
    ],
  },
  {
    id: "5",
    nama: "Monas",
    deskripsi:
      "Siapa yang tidak tahu dengan ikon Utama Kota Jakarta yang satu ini? Monas atau yang dikenal sebagai monument nasional, merupakan salah satu bangunan bersejarah yang diresmikan pada tahun 1961 telah menyimpan banyak sekali cerita sejarah Ibu Kota. Monas sendiri dibangun untuk mengenang dan melestarikan perjuangan bangsa Indonesia pada masa revolusi kemerdekaan 1945, agar membangkitkan inspirasi dan semangat patriotisme generasi saat ini dan mendatang. Dengan tinggi 132 meter serta dihiasi puncak api yang melambangkan semangat dan perjuangan Indonesia menjadikannya sangat cocok sebagai landmark Ibu Kota. Monas juga  tidak hanya menjadi tujuan wisata populer bagi wisatawan lokal dan internasional, tetapi juga menjadi tempat untuk berbagai acara dan perayaan nasional, seperti peringatan Hari Kemerdekaan Indonesia pada tanggal 17 Agustus setiap tahunnya. Sebagai simbol nasional, Monas memiliki nilai historis dan simbolis yang sangat penting bagi bangsa Indonesia. Monas juga menjadi pusat kegiatan budaya dan acara-acara nasional, seperti perayaan Hari Kemerdekaan Indonesia yang diadakan setiap tahunnya. Dengan sejarahnya yang kaya dan pemandangannya yang menakjubkan, Monas tetap menjadi destinasi yang wajib dikunjungi bagi siapa pun yang ingin mengenal lebih dekat keindahan dan keberagaman Indonesia.",
    kategori: "Taman Hiburan dan Edukasi",
    lokasi: "Jakarta Pusat",
    Alamat: "RT.5/RW.2, Gambir, Central Jakarta City, Jakarta 10110",
    Instagram: "@monumen.nasional",
    JamOp: "Selasa - Minggu : 08.00 - 15.00 [Tugu Monas], 06.00 - 16.00 [Kawasan Monas]",
    image: "/assets/monas.jpg",
    images: [
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
    ],
  },
  {
    id: "6",
    nama: "Masjid Istiqlal",
    deskripsi:
      "Masjid Istiqlal di Jakarta, Indonesia adalah masjid terbesar di Asia Tenggara dan masjid terbesar kesembilan di dunia dalam hal kapasitas jamaah. Dibangun untuk memperingati kemerdekaan Indonesia, masjid nasional Indonesia ini diberi nama 'Istiqlal', sebuah kata Arab untuk 'kemerdekaan'.",
    kategori: "Agama",
    lokasi: "Jakarta Pusat",
    Alamat: "Jl. Taman Wijaya Kusuma, Ps. Baru, Kecamatan Sawah Besar, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10710",
    Instagram: "@masjidistiqlal.official",
    JamOp: "04:00 - 21:00 WIB",
    image: "/assets/istiqlal.webp",
    images: [
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
    ],
  },
  {
    id: "7",
    nama: "Katedral Jakarta",
    deskripsi:
      "Katedral Jakarta adalah sebuah katedral Katolik Roma di Jakarta, Indonesia, yang juga merupakan tempat kedudukan Uskup Agung Katolik Roma Jakarta, yang saat ini menjabat sebagai Uskup Agung Ignatius Suharyo Hardjoatmodjo.",
    kategori: "Agama",
    lokasi: "Jakarta Pusat",
    Alamat: "Jl. Katedral No.7B, Ps. Baru, Kecamatan Sawah Besar, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10710",
    Instagram: "@katedraljakarta",
    JamOp: "Senin			: Tutup \nSelasa - Sabtu	: 10.00 - 16.00 WIB \nMinggu		: Sesuai perjanjian",
    image: "/assets/katedral.png",
    images: [
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
    ],
  },
  {
    id: "8",
    nama: "Hutan Kota GBK",
    deskripsi:
      "Area hijau dengan beragam lapangan olahraga & stadion bisbol, serta restoran & area piknik.",
    kategori: "Rekreasi",
    lokasi: "Jakarta Pusat",
    Alamat: "Jl. Katedral No.7B, Ps. Baru, Kecamatan Sawah Besar, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10710",
    Instagram: "@hutankota.gbk",
    JamOp: "Selasa - Minggu	: 06.00-10.00 WIB dan 15.00-18.00 WIB.",
    image: "/assets/hutangbk.png",
    images: [
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
    ],
  },
  {
    id: "9",
    nama: "Taman Wisata Alam Mangrove Angke Kapuk",
    deskripsi:
      "Suaka margasatwa ini memiliki banyak pohon bakau, binatang-binatang seperti monyet, dan beragam burung.",
    kategori: "Rekreasi",
    lokasi: "Jakarta Pusat",
    Alamat: "Jalan Garden House, Kamal Muara, Kecamatan Penjaringan, Daerah Khusus Ibukota Jakarta 14470, Indonesia.",
    Instagram: "@twa_mangrove",
    JamOp: "08.00 WIB - 17.30 WIB.",
    image: "/assets/Mangrove.jpeg",
    images: [
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
    ],
  },
  {
    id: "10",
    nama: "Pantjoran Pantai Indah Kapuk",
    deskripsi:
      "Kumpulan bangunan dengan desain penuh hiasan yang mengingatkan pada Chinatown kuno, dengan toko makanan dan pedagang kaki lima.",
    kategori: "Rekreasi",
    lokasi: "Jakarta Utara",
    Alamat: "Pantjoran PIK, Daerah Khusus Ibukota Jakarta 14460, Indonesia.",
    Instagram: "@pantjoranpik",
    JamOp: "Selasa - Minggu : 07.00 - 23.00 WIB.",
    image: "/assets/PIK.jpg",
    images: [
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
      "/assets/",
    ],
  },
];

module.exports = { destinations };
